# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Daytona < Formula
  desc ""
  homepage "https://daytona.io/"
  version "0.7"

  on_macos do
    url "https://github.com/idagelic/TempDTN2/releases/download/v0.7/TempDTN2_0.7_darwin_all.tar.gz"
    sha256 "f1e53c132a5bee1b0cb3bd3fbfa9f45c7a5c1e608100438f67ec5dc21fc6d1e2"

    def install
      bin.install "TempDTN2"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/idagelic/TempDTN2/releases/download/v0.7/TempDTN2_0.7_linux_amd64.tar.gz"
      sha256 "c9b2162499168381735145e49cb6406a28919d7e6bc24111d9befec5b3fc77f4"

      def install
        bin.install "daytona"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/idagelic/TempDTN2/releases/download/v0.7/TempDTN2_0.7_linux_arm64.tar.gz"
      sha256 "a7c57b3c6ad60f114bb04a96cc33aa4d4007c84ef07cbc67b6fedf2d93a2f40b"

      def install
        bin.install "daytona"
      end
    end
  end
end
