# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Daytona < Formula
  desc ""
  homepage "https://daytona.io/"
  version "1.5"

  on_macos do
    url "https://github.com/idagelic/TempDTN2/releases/download/v1.5/TempDTN2_1.5_darwin_all.tar.gz"
    sha256 "16cde4c076cde53ab00be973c8998746b1029f2ac15f82ecd64d6ef6eccd1593"

    def install
      bin.install "TempDTN2"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/idagelic/TempDTN2/releases/download/v1.5/TempDTN2_1.5_linux_arm64.tar.gz"
      sha256 "d44e03d2915c337ebe16fcd0b841ec6527bbbb15071c32e3a4b76e90b804e03b"

      def install
        bin.install "daytona"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/idagelic/TempDTN2/releases/download/v1.5/TempDTN2_1.5_linux_amd64.tar.gz"
      sha256 "90a5f121a0df10e21ef9729faca5e9c191eafe450282fdc53ea08443298092e1"

      def install
        bin.install "daytona"
      end
    end
  end
end
